# Site settings
author: Juliana Mercer Fogg
title: Becoming a Developer
header-img: img/home-bg.png
email: julianafogg@gmail.com
copyright_name: Juliana Mercer Fogg
description: > # this means to ignore newlines until "baseurl:"
  Think. Code. Create
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MERCERNYC

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
