# Site settings
title: Project Mercer
header-img: img/home-bg.png
email: julianafogg@gmail.com
copyright_name: MERCERNYC
description: > # this means to ignore newlines until "baseurl:"
  Create & Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MERCERNYC
learn_profile: MERCERNYC
email_username: julianafogg@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
